/*
    Copyright (C) 2014 Omega software d.o.o.

    This file is part of Rhetos.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

using Rhetos.Utilities.ApplicationConfiguration;
using System.IO;
using System.Reflection;

namespace Rhetos.Utilities
{
    /// <summary>
    /// Run-time environment.
    /// </summary>
    public class RhetosAppEnvironment
    {
        /// <summary>
        /// Initializes RhetosAppEnvironment from runtime configuration:
        /// * ApplicationRootFolder (provided by host application)
        /// * RhetosRuntimePath (from configuration file generated at build-time, required)
        /// * AssetsFolder (from configuration file generated by build, required)
        /// * Legacy__PluginsFolders (from configuration file generated by build, optional)
        /// </summary>
        public static RhetosAppEnvironment FromRuntimeConfiguration(IConfigurationProvider configuration)
        {
            var appRootFolder = configuration.GetValue<string>(nameof(ApplicationRootFolder));
            if (string.IsNullOrEmpty(appRootFolder))
                throw new FrameworkException($"Missing '{nameof(ApplicationRootFolder)}' configuration setting. Please verify that the Rhetos build have passed successfully.");

            var appConfiguration = configuration.GetOptions<RhetosAppConfiguration>();
            if (string.IsNullOrEmpty(appConfiguration.RhetosRuntimePath))
                throw new FrameworkException($"Missing '{nameof(RhetosAppConfiguration.RhetosRuntimePath)}' configuration setting. Please verify that the Rhetos build have passed successfully.");
            if (string.IsNullOrEmpty(appConfiguration.AssetsFolder))
                throw new FrameworkException($"Missing '{nameof(RhetosAppConfiguration.AssetsFolder)}' configuration setting. Please verify that the Rhetos build have passed successfully.");

            return new RhetosAppEnvironment
            {
                ApplicationRootFolder = Path.GetFullPath(appRootFolder),
                RhetosRuntimePath = Path.GetFullPath(appConfiguration.RhetosRuntimePath),
                AssemblyFolder = Path.GetFullPath(Path.GetDirectoryName(appConfiguration.RhetosRuntimePath)),
                AssetsFolder = Path.GetFullPath(appConfiguration.AssetsFolder),
                AssemblyName = Assembly.Load(appConfiguration.RhetosRuntimePath).GetName().Name,
                Legacy__PluginsFolder = appConfiguration.Legacy__PluginsFolders != null ? Path.GetFullPath(appConfiguration.Legacy__PluginsFolders) : null,
            };
        }

        public string ApplicationRootFolder { get; set; }

        public string RhetosRuntimePath { get; set; }

        public string AssemblyFolder { get; set; }

        public string AssetsFolder { get; set; }

        /// <summary>
        /// Assembly that contains the generated object model.
        /// Null for old Rhetos applications with multiple generated ServerDom libraries.
        /// </summary>
        public string AssemblyName { get; set; }

        /// <summary>
        /// This folder can be configured to support legacy plugins.
        /// Null for new Rhetos applications, where plugins are placed in <see cref="AssemblyFolder"/> by NuGet.
        /// </summary>
        public string Legacy__PluginsFolder { get; set; }
    }
}
