/*
    Copyright (C) 2014 Omega software d.o.o.

    This file is part of Rhetos.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Rhetos.Dsl;
using System.ComponentModel.Composition;
using Rhetos.Utilities;

namespace Rhetos.Dsl.DefaultConcepts
{
    /// <summary>
    /// Creates a property on the browse data structure that returns the property value from the base data structure.
    /// Instead of a simple property, it is possible to specify a path across multiple references, separated by a dot.
    /// The resulting property name is automatically generated by connecting the names from the path 
    /// (e.g. Take 'Parent.Organization.Name' will result with property ParentOrganizationName).
    /// </summary>
    [Export(typeof(IConceptInfo))]
    [ConceptKeyword("Take")]
    public class BrowseTakePropertyInfo : BrowseTakeNamedPropertyInfo, IAlternativeInitializationConcept
    {
        public IEnumerable<string> DeclareNonparsableProperties()
        {
            return new[] { "Name" };
        }

        public void InitializeNonparsableProperties(out IEnumerable<IConceptInfo> createdConcepts)
        {
            Name = Path.Replace(".", "");
            createdConcepts = null;
        }
    }
}
