/*DATAMIGRATION D823DFF8-BE69-46DF-A6C9-02676C980C71*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'TestFullTextSearch', 'Simple_Search';
EXEC Rhetos.DataMigrationUse 'TestFullTextSearch', 'SimpleFTS', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'TestFullTextSearch', 'Simple_Search', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'TestFullTextSearch', 'Simple', 'ID', 'uniqueidentifier';
GO

DELETE FROM _TestFullTextSearch.SimpleFTS;
DELETE FROM _TestFullTextSearch.Simple_Search;
DELETE FROM _TestFullTextSearch.Simple;

EXEC Rhetos.DataMigrationApplyMultiple 'TestFullTextSearch', 'SimpleFTS', 'ID';
EXEC Rhetos.DataMigrationApplyMultiple 'TestFullTextSearch', 'Simple_Search', 'ID';
EXEC Rhetos.DataMigrationApplyMultiple 'TestFullTextSearch', 'Simple', 'ID';
