/*
    Copyright (C) 2014 Omega software d.o.o.

    This file is part of Rhetos.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

using System.Linq;

namespace CommonConcepts.Test
{
    public static class EntityFrameworkExtensions
    {
        /// <summary>
        /// Returns the SQL query generated by Entity Framework.
        /// This method helps with compatibility of EF6 method "ToString" and EF Core method "ToQueryString", to allow the same C# code when testing both ORM frameworks.
        /// </summary>
        public static string GetSqlQuery(this IQueryable query)
        {
#if RHETOS_EF6
            return query.ToString();
#else
            return Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(query);
#endif
        }
    }
}
