using System.Linq;

namespace CommonConcepts.Test
{
    public static class EntityFrameworkExtensions
    {
        /// <summary>
        /// Returns the SQL query generated by Entity Framework.
        /// This method helps with compatibility of EF6 method "ToString" and EF Core method "ToQueryString", to allow the same C# code when testing both ORM frameworks.
        /// </summary>
        public static string GetSqlQuery(this IQueryable query)
        {
#if RHETOS_EF6
            return query.ToString();
#else
            return Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(query);
#endif
        }
    }
}
