/*DATAMIGRATION 0D99CDE7-E4CB-4FBF-937B-4ADEEEBC46CE*/ -- Change the script's code only if the it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Common', 'RoleInheritsRole';
EXEC Rhetos.DataMigrationUse 'Common', 'RoleInheritsRole', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Common', 'RoleInheritsRole', 'DerivedID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Common', 'RoleInheritsRole', 'InheritsFromID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Common', 'RoleInheritsRole', 'UsersFromID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Common', 'RoleInheritsRole', 'PermissionsFromID', 'uniqueidentifier';
GO

-- ... write the data migration queries here (don't forget to use the underscore '_' in schema name) ...

UPDATE
	_Common.RoleInheritsRole
SET
	UsersFromID = DerivedID,
	PermissionsFromID = InheritsFromID
WHERE
	UsersFromID IS NULL AND PermissionsFromID IS NULL;

EXEC Rhetos.DataMigrationApplyMultiple 'Common', 'RoleInheritsRole', 'ID, UsersFromID, PermissionsFromID';
